"""Build the author-review data archive; does not grant redistribution rights."""
from __future__ import annotations
import argparse
import gzip
import hashlib
import io
import json
from pathlib import Path
import subprocess
import tarfile

INPUTS = Path('outputs/final_runs/paper1_canonical_inputs')
RESULTS = Path('outputs/final_runs/paper1_canonical_results')
FINAL = {'paper1_manuscript_values.json', 'pv_model_comparison.json', 'conditional_uncertainty.json'}


def selected_files(root):
    paths = set()
    def add(pattern):
        paths.update(p for p in root.glob(pattern) if p.is_file())
    for pattern in ('aef/*.csv', 'manifest/*', 'par/par_wide.csv', 'par/par_imputed_flags.csv'):
        add(f'{INPUTS}/{pattern}')
    # Regional inputs support static-grid/fuel/storage analyses; national inputs
    # support the merit-order lens and the manuscript's data-quality audit.
    for pattern in ('*_unit_generation.csv', 'unit_generation_imputed_flags.csv',
                    '*gap_report.csv', '*quality_report.json', '*timestamp_normalization.csv',
                    'generation_invalid_total_report.csv', 'unit_capacity.csv',
                    'unit_generation.csv', 'category_generation.csv', 'flow.csv'):
        add(f'{INPUTS}/power/{pattern}')
    for pattern in ('data/geo/municipal_population_2024.json',
                    'outputs/paper_assets/paper1/figure_data/*.csv'):
        add(pattern)
    # The full baseline candidate panel is reusable; large alternative-scenario
    # panels are regenerated by their analysis scripts, not shipped redundantly.
    paths.update(p for p in (root / RESULTS).rglob('*')
                 if p.is_file() and p.suffix in {'.csv', '.json'}
                 and (p.stat().st_size < 2 * 1024**2 or p.parent.name == 'pareto'))
    for required in (INPUTS / 'par/par_wide.csv', RESULTS / 'pareto/results.csv',
                     RESULTS / 'paper1_manuscript_values.json',
                     RESULTS / 'allocation_sensitivity/summary.json',
                     RESULTS / 'allocation_sensitivity/scenario_summary.csv',
                     RESULTS / 'allocation_sensitivity/regional_summary.csv',
                     RESULTS / 'allocation_sensitivity/city_results.csv',
                     RESULTS / 'allocation_sensitivity/allocation_shares.csv'):
        if root / required not in paths:
            raise FileNotFoundError(required)
    return sorted(paths)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--dry-run', action='store_true')
    args = parser.parse_args()
    root = args.source.resolve()
    paths = selected_files(root)
    summary = {'files': len(paths), 'uncompressed_bytes': sum(p.stat().st_size for p in paths)}
    if args.dry_run:
        print(json.dumps(summary)); return
    weather = []
    for path in sorted(root.glob('outputs/final_runs/paper1_pv_benchmark_inputs/met_*.json')):
        payload = json.loads(path.read_bytes())
        _, latitude, longitude = path.stem.split('_')
        parameters = json.dumps(payload['properties']['parameter'], sort_keys=True, separators=(',', ':')).encode()
        weather.append({'path': path.relative_to(root).as_posix(),
                        'latitude': float(latitude), 'longitude': float(longitude),
                        'parameter_sha256': hashlib.sha256(parameters).hexdigest(),
                        'original_file_sha256': hashlib.sha256(path.read_bytes()).hexdigest()})
    if len(weather) != 14:
        raise ValueError(f'Expected 14 meteorological grid cells, found {len(weather)}')
    boundaries = []
    for suffix in ('.cpg', '.dbf', '.prj', '.shp', '.shx'):
        path = root / ('data/geo/county_boundaries' + suffix)
        boundaries.append({'path': path.relative_to(root).as_posix(),
                           'member': 'COUNTY_MOI_1140318' + ('.CPG' if suffix == '.cpg' else suffix),
                           'sha256': hashlib.sha256(path.read_bytes()).hexdigest()})
    args.output.parent.mkdir(parents=True, exist_ok=True)
    records = []
    args.output.unlink(missing_ok=True)
    with args.output.open('wb') as raw, gzip.GzipFile(filename='', fileobj=raw, mode='wb', mtime=0) as gz, tarfile.open(fileobj=gz, mode='w') as tar:
        def write(name, data):
            info = tarfile.TarInfo(name)
            info.size, info.mode, info.mtime = len(data), 0o644, 0
            tar.addfile(info, io.BytesIO(data))
        for path in paths:
            relative = path.relative_to(root).as_posix()
            data = path.read_bytes()
            # Immutable expected answers live apart from executable work paths.
            name = f'reference/{relative}'
            records.append({'path': name, 'source_path': relative,
                            'bytes': len(data), 'sha256': hashlib.sha256(data).hexdigest(),
                            'role': 'expected_answer' if path.name in FINAL else 'input_or_intermediate'})
            write(name, data)
        commit = subprocess.check_output(['git', '-C', str(root), 'rev-parse', 'HEAD'], text=True).strip()
        manifest = {'schema_version': 2, 'status': 'LOCAL_AUTHOR_REVIEW_NOT_CLEARED_FOR_PUBLICATION',
                    'external_weather': weather, 'external_boundaries': boundaries,
                    'source_commit': commit, 'files': records,
                    'rights': 'See docs/data-bundle.md. No blanket data license is granted.',
                    'scope': 'Processed inputs and frozen intermediates; not raw-data reconstruction.'}
        write('bundle.json', (json.dumps(manifest, indent=2) + '\n').encode())
    digest = hashlib.sha256(args.output.read_bytes()).hexdigest()
    args.output.with_suffix(args.output.suffix + '.sha256').write_text(f'{digest}  {args.output.name}\n')
    print(json.dumps({**summary, 'archive_bytes': args.output.stat().st_size, 'sha256': digest}))

if __name__ == '__main__':
    main()
